name: MasterInventory
main: com.danielmaslia.masterinventory.MasterInventory
version: ${project.version}
api-version: 1.21
commands:
  getinv:
    description: gets inventory
    usage: /getinv
  chat:
    description: calls chat
    usage: /chat
  save:
    description: saves coordinates
    usage: /save <x> <y> <z> <description>
  remind:
    description: sets a reminder
    usage: /remind [timer_dur] message
  add:
    description: adds the players chunk to the scanned chunks
    usage: /add
  remove:
    description: removes the players chunk from the scanned chunks
    usage: /remove
  p:
    description: takes player out of chat session
    usage: /p [chat]
  addmobs:
    description: registers all named mobs for tracking
    usage: /addmobs
  add_world:
    description: links a portal to a world teleport
    usage: /add_world <world_name> [gamemode]
  exit:
    description: teleports back to the main world portal
    usage: /exit
  remove_world:
    description: unlinks a portal from a world teleport
    usage: /remove_world
